parameters:
#    schooltrip.example.class: AthenaPlus\SchooltripBundle\Example

services:
#    schooltrip.example:
#        class: %schooltrip.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
