<?php

namespace AthenaPlus\SchooltripBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabRepository extends EntityRepository
{
}
